resolve form fields
js-tasks-ru/htmlcss-20211125_daryaryab pull request #19
Opened 2021-12-22 20:51 UTC by daryabagmet

2021-12-22 20:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-22 20:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-26 11:19 UTC, GSemikozov requested changes

2021-12-26 11:19 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <label class="field">
здесь я бы советовал не заворачивать в label а связать через id-for - поскольку иногда нам потребуется добавлять различные кликабельные элементы, что будет в конфликте с тем что и сам label кликабелен

2021-12-26 11:19 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <input type="text" class="field__input field__input_invalid" value="Error" />
и еще инпут и иконки я бы наоборот завернул во враппер - чтобы при позиционировании иконок не привязываться к значению высоты label

2022-01-03 08:57 UTC, daryabagmet commented on 07-lection5/04-input/index.html
> +            <label class="field">
поправила

2022-01-03 08:58 UTC, daryabagmet commented on 07-lection5/04-input/index.html
> +                <input type="text" class="field__input field__input_invalid" value="Error" />
поправила

2022-01-03 15:34 UTC, GSemikozov requested changes

2022-01-03 15:34 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <label class="field__label" for="input4">Error</label>
не совсем то о чем было написано)

все элементы блока должны быть внутри блока, поэтому как вариант разметку можно оформить так:

```
            <div class="field field_success">
               <label class="field__label" for="input2">Success</label>
                <span class="field__wrap"> 
                    <input id="input2" type="text" class="field__input" value="Success" />
                    <img class="field__icon field__icon_invalid" src="../../assets/images/error-icon.svg" alt="error" />
                    <img class="field__icon field__icon_success" src="../../assets/images/success-icon.svg" alt="success" />
                    </span>
            </div>
```

2022-01-06 06:25 UTC, daryabagmet commented on 07-lection5/04-input/index.html
> +            <label class="field__label" for="input4">Error</label>
исправила)

2022-01-06 12:13 UTC, GSemikozov requested changes

2022-01-06 12:13 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    margin: 0 0 16px;
вот только с марджинами опять поспешили)
марджины добавим через миксы когда будем встраивать поля форм в собственно форму

2022-01-07 09:25 UTC, daryabagmet commented on 07-lection5/04-input/input.css
> +    margin: 0 0 16px;
поправила

2022-01-07 20:31 UTC, GSemikozov approved these changes

2022-01-07 20:31 UTC, merged