resolve 01 button
js-tasks-ru/htmlcss-20211125_daryaryab pull request #3
Opened 2021-12-04 10:20 UTC by daryabagmet

2021-12-04 10:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-05 15:50 UTC, GSemikozov requested changes

2021-12-05 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons {
мышление в сторону использования миксов правильное, единственное - в файле компонента мы описываем только сам компонент с его модификаторами и элементами, другие блоки должны быть описаны в других файлах. В данном случае эти классы вспомогательные и будут использоваться только в хтмл для демонстрации выполненной домашки, поэтому - их можно переместить прямо в этот хтмл в тег style

2021-12-05 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  min-height: 48px;
можно просто height - мы не хотим. чтобы кнопка увеличивалась по высоте в зависимости от внутреннего. содержимого)

2021-12-05 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px;
соответствуют ли макету?

2021-12-05 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  background-color: #4263EB;
тут и ниже - все цвета вставляем как css-переменные

2021-12-05 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_type_primary.button_disabled:hover {
.button_type_primary -> .button_primary

2021-12-05 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_type_primary.button_disabled:hover {
.button_type_primary.button_disabled:hover - при disabled пользователь не должен иметь возможность взаимодействовать с элементом, то есть не будет ховера

2021-12-05 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  border: 1px solid #2342C0;
чтобы меньше писать и меньше переопределять - можно менять толко border-color

2021-12-05 15:50 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: not-allowed;
чтобы пользователь не мог взаимодействовать с такие элементом добавляем pointer-events: none

2021-12-06 08:42 UTC, daryabagmet commented on 03-lection1/01-button/button.css
> +  padding: 15px;
не совсем поняла где ошибка, макет посмотрела - не нашла

2021-12-06 08:42 UTC, daryabagmet commented on 03-lection1/01-button/button.css
> +.buttons {
поправила

2021-12-06 08:42 UTC, daryabagmet commented on 03-lection1/01-button/button.css
> +  background-color: #4263EB;
поправила

2021-12-06 08:42 UTC, daryabagmet commented on 03-lection1/01-button/button.css
> +.button_type_primary.button_disabled:hover {
убрала

2021-12-06 08:42 UTC, daryabagmet commented on 03-lection1/01-button/button.css
> +  border: 1px solid #2342C0;
не совсем поняла, как это

2021-12-06 08:43 UTC, daryabagmet commented on 03-lection1/01-button/button.css
> +  cursor: not-allowed;
поправила

2021-12-09 11:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px;
в макете сверху 15 а снизу 14)

2021-12-09 11:15 UTC, GSemikozov requested changes

2021-12-09 11:15 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import '../../assets/css/main.css';
глобальный файл подключается один раз на уровне страницы, не стоит его импортировать в каждый компонент (стили компонента не инкапсулированы и не закрыты самим компонентом, они "видят"  стили из других файлов)

2021-12-09 11:58 UTC, daryabagmet commented on 03-lection1/01-button/button.css
> +  min-height: 48px;
поправила

2021-12-09 12:33 UTC, daryabagmet commented on 03-lection1/01-button/button.css
> +@import '../../assets/css/main.css';
поправила

2021-12-09 12:33 UTC, daryabagmet commented on 03-lection1/01-button/button.css
> +  padding: 15px;
поправила

2021-12-09 16:05 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  border: 1px solid #2342C0;
border: 1px solid #2342C0 - из всего этого по сравнению с дефолтным состоянием меняется только цвет, то есть не border-width, не border-style, а border-color :)

2021-12-10 19:04 UTC, daryabagmet commented on 03-lection1/01-button/button.css
> +  border: 1px solid #2342C0;
теперь поняла) спасибо)
 поправила

2021-12-13 15:32 UTC, GSemikozov approved these changes

2021-12-13 15:32 UTC, merged