basic layout
js-tasks-ru/htmlcss-20211125_daryaryab pull request #5
Opened 2021-12-05 09:38 UTC by daryabagmet

2021-12-05 09:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-05 15:55 UTC, GSemikozov requested changes

2021-12-05 15:55 UTC, GSemikozov commented on assets/css/main.css
> +    max-width: 1130px;
1110

2021-12-05 15:55 UTC, GSemikozov commented on assets/css/main.css
> +    padding: 70px;
тут лучше сразу как по макету)

2021-12-05 15:55 UTC, GSemikozov commented on assets/css/main.css
> +.header {
компонент header нужно унести в `components/header/header.css`

2021-12-05 15:55 UTC, GSemikozov commented on assets/css/main.css
> +.footer {
переместим в `components/footer/footer.css`

2021-12-06 08:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-06 08:18 UTC, daryabagmet commented on assets/css/main.css
> +    max-width: 1130px;
fixed

2021-12-06 08:18 UTC, daryabagmet commented on assets/css/main.css
> +    padding: 70px;
fixed

2021-12-06 08:18 UTC, daryabagmet commented on assets/css/main.css
> +.header {
fixed

2021-12-06 08:19 UTC, daryabagmet commented on assets/css/main.css
> +.footer {
fixed

2021-12-06 08:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-06 08:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-09 11:10 UTC, GSemikozov requested changes

2021-12-09 11:10 UTC, GSemikozov commented on components/cards.css
> +  width: 300px;
достаточно ширины родителя

2021-12-09 11:10 UTC, GSemikozov commented on components/cards.css
> +.cards {
вот это - скорее тот самый компонент .preview.  Можно и cards,  но тогда card-item (можно просто card) - это уже совсем другой компонент,  его нужно описывать отдельно

2021-12-10 11:03 UTC, GSemikozov requested changes

2021-12-10 11:03 UTC, GSemikozov commented on components/header.css
> +    padding: 96px 160px 77px;
если используем контейнер для внутреннего содержимого, то эти паддинги по краям не нужны (160)

2021-12-10 11:03 UTC, GSemikozov commented on components/footer.css
> +    padding: 70px;
здесь тот же случай что и с хедером - если сверху и снизу можем проставить паддинги, то слева-справа - не нужно

2021-12-10 19:01 UTC, daryabagmet commented on components/header.css
> +    padding: 96px 160px 77px;
поправила

2021-12-10 19:01 UTC, daryabagmet commented on components/footer.css
> +    padding: 70px;
поправила

2021-12-13 15:35 UTC, GSemikozov submitted a review, later dismissed

2021-12-13 15:35 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-12-16 11:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-16 11:19 UTC, closed without merging