resolve skeleton
js-tasks-ru/htmlcss-20211125_daryaryab pull request #7
Opened 2021-12-08 10:34 UTC by daryabagmet

2021-12-08 10:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-08 10:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-08 10:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-09 12:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-09 12:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-09 12:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-10 11:06 UTC, GSemikozov requested changes

2021-12-10 11:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +@import '../../assets/css/main.css';
файл подключен глобально, дополнительно подключать в компонент не надо

2021-12-10 11:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  margin: 0 0 8px;
тут снизу точно нужен отступ?)

2021-12-10 11:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  gap: 8px
нет `;`

2021-12-10 11:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  max-width: 172px;
поправить имена модификаторов - .skeleton_row_small -> .skeleton__row_small

2021-12-10 11:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  max-width: 172px;
а также указать ширину в процентах

2021-12-11 06:27 UTC, daryabagmet commented on 04-lection2/02-skeleton/skeleton.css
> +@import '../../assets/css/main.css';
поправила

2021-12-11 06:27 UTC, daryabagmet commented on 04-lection2/02-skeleton/skeleton.css
> +  margin: 0 0 8px;
убрала)

2021-12-11 06:28 UTC, daryabagmet commented on 04-lection2/02-skeleton/skeleton.css
> +  gap: 8px
добавила)

2021-12-11 06:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-11 06:28 UTC, daryabagmet commented on 04-lection2/02-skeleton/skeleton.css
> +  max-width: 172px;
поправила

2021-12-11 13:10 UTC, GSemikozov approved these changes

2021-12-11 13:10 UTC, merged